# Generated by Django 5.2.1 on 2025-05-14 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranchsmart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potrero',
            name='pasto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='potreros', to='ranchsmart.pasto'),
        ),
    ]
