# Generated by Django 5.2.1 on 2025-05-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranchsmart', '0002_alter_potrero_pasto'),
    ]

    operations = [
        migrations.AddField(
            model_name='potrero',
            name='estado',
            field=models.CharField(choices=[(0, 'Inactivo'), (1, 'En descanso'), (2, 'Ocupado')], default=0, max_length=10),
        ),
    ]
