# Generated by Django 5.2.1 on 2025-05-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranchsmart', '0003_potrero_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='potrero',
            name='area_m2',
            field=models.FloatField(default=0),
        ),
    ]
