# Generated by Django 5.2.1 on 2025-05-17 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranchsmart', '0005_precipitacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='AforoPasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('materia_seca_kg_ha', models.FloatField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('potrero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aforos', to='ranchsmart.potrero')),
            ],
        ),
    ]
